# Copyright (c) 2016 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

description: Apps and Engines when toolkit is run from outside a project.

#################################################################################################
# define all the items that should appear in this environment
# By default make the non-project side of the desktop engine available

engines:

  tk-maya:
    apps:

      tk-multi-loader2:
        action_mappings:
          Maya Scene: [reference, import]
          Photoshop Image: [texture_node]
          Rendered Image: [texture_node]
        actions_hook: '{self}/tk-maya_actions.py'
        download_thumbnails: true
        entities:
        - caption: Assets
          entity_type: Asset
          filters:
          - [project, is, '{context.project}']
          hierarchy: [sg_asset_type, code]
        - caption: Shots
          entity_type: Shot
          filters:
          - [project, is, '{context.project}']
          hierarchy: [sg_sequence, code]
        - caption: My Tasks
          entity_type: Task
          filters:
          - [task_assignees, is, '{context.user}']
          - [project, is, '{context.project}']
          hierarchy: [entity, content]
        filter_publishes_hook: '{self}/filter_publishes.py'
        location:
          version: v1.11.2
          type: app_store
          name: tk-multi-loader2
        menu_name: Load
        publish_filters: []
        title_name: Loader

#      tk-multi-shotgunpanel:
#        location:
#          version: v1.2.5
#          type: app_store
#          name: tk-multi-shotgunpanel
#        shotgun_fields_hook: '{self}/shotgun_fields.py'
#        actions_hook: '{self}/general_actions.py'
#        action_mappings:
#          PublishedFile:
#          - actions:
#            - publish_clipboard
#            filters: {}
#          Task:
#          - actions:
#            - assign_task
#            - task_to_ip
#            filters: {}
#          Version:
#          - actions:
#            - quicktime_clipboard
#            - sequence_clipboard
#            filters: {}



    compatibility_dialog_min_version: 2015
    debug_logging: true
    location:
      version: 92cd8e3b8bb8f2d0831d45b5215ac37eef9f6e86
      type: git_branch
      branch: 37277_site_context_maya
      path: git@github.com:shotgunsoftware/tk-maya.git
    menu_favourites: []
    template_project:
    use_sgtk_as_menu_name: false


frameworks:
  tk-framework-qtwidgets_v2.x.x:
    location:
      version: v2.3.3
      type: app_store
      name: tk-framework-qtwidgets
  tk-framework-shotgunutils_v4.x.x:
    location:
      version: v4.3.1
      type: app_store
      name: tk-framework-shotgunutils
